if(TARGET ZLIB::ZLIB AND DEFINED EUI_ZLIB_DIR AND EXISTS "${EUI_ZLIB_DIR}/zlib.h")
    set(ZLIB_FOUND TRUE)
    set(ZLIB_INCLUDE_DIRS "${EUI_ZLIB_DIR}")
    set(ZLIB_LIBRARIES ZLIB::ZLIB)
    set(ZLIB_LIBRARY ZLIB::ZLIB)
    set(ZLIB_INCLUDE_DIR "${EUI_ZLIB_DIR}")

    file(STRINGS "${EUI_ZLIB_DIR}/zlib.h" _eui_zlib_version_line REGEX "^#define ZLIB_VERSION ")
    string(REGEX REPLACE "^#define ZLIB_VERSION \"([^\"]+)\".*$" "\\1" ZLIB_VERSION_STRING "${_eui_zlib_version_line}")
    set(ZLIB_VERSION "${ZLIB_VERSION_STRING}")
else()
    include("${CMAKE_ROOT}/Modules/FindZLIB.cmake")
endif()
