if(TARGET PNG::PNG)
    set(PNG_FOUND TRUE)
    set(PNG_LIBRARIES PNG::PNG)
    get_target_property(PNG_INCLUDE_DIRS PNG::PNG INTERFACE_INCLUDE_DIRECTORIES)
    if(NOT PNG_INCLUDE_DIRS)
        set(PNG_INCLUDE_DIRS "")
    endif()
    set(PNG_DEFINITIONS "")
else()
    include("${CMAKE_ROOT}/Modules/FindPNG.cmake")
endif()
